axon:
  axonserver:
    servers: ${AXON_HOST}
    keep-alive-time: 0
    ssl-enabled: true
    context: ${AXON_CONTEXT}
    token: ${AXON_TOKEN}
  serializer:
    messages: jackson
    events: jackson
    general: jackson
  mongo:
    token-store:
      enabled: true
    saga-store:
      enabled: false
    event-store:
      enabled: false
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}